# version: "3.8"

services:
  auto-dns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-dns
    env_file:
      - ./.env
    hostname: auto-dns
    image: erdong/auto-dns:latest
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - ./runtime:/app/runtime
